#server:
#  port: 8888
#spring:
#  profiles:
#    active: prod
#  application:
#    name: tanhua-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.212.111:8848
#    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTION
#      # 配置路由
#      # 探花系统 - tanhua-app-server
#      # 后台系统 - tanhua-admin
#      routes:
#        - id: tanhua-app-server
#          uri:  lb://tanhua-app-server
#          predicates:
#            - Path=/app/**
#          filters:
#            - StripPrefix=1
#        - id: tanhua-admin
#          uri: lb://tanhua-admin
#          predicates:
#            - Path=/admin/**
#          filters:
#            - StripPrefix=1
#            -
#gateway:
#  excludedUrls: /user/login,/user/loginVerification,/system/users/verification,/system/users/login