server:
  port: 18082
spring:
  application:
    name: tanhua-dubbo-mongo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.212.111:8848
  data:
    mongodb:
      uri: mongodb://192.168.212.111:27017/tanhua
dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.aomsir.dubbo.api  #dubbo中包扫描